#!/bin/sh
#
# /etc/rc.d/iptabes: start/stop iptables
#

case $1 in
start)
    iptables -F
    iptables -X
    iptables -Z

    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT ACCEPT

    iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A INPUT -p icmp --icmp-type 3 -j ACCEPT
    iptables -A INPUT -p icmp --icmp-type 11 -j ACCEPT
    iptables -A INPUT -p icmp --icmp-type 12 -j ACCEPT
    iptables -A INPUT -p tcp --syn --dport 113 -j REJECT --reject-with tcp-reset

    iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    ;;
stop)
    iptables -F
    iptables -X
    iptables -t nat -F
    iptables -t nat -X
    iptables -P INPUT ACCEPT
    iptables -P FORWARD ACCEPT
    iptables -P OUTPUT ACCEPT
    ;;
restart)
    $0 stop
    $0 start
    ;;
status)
    iptables --list
    ;;
*)
    echo "usage: $0 [start|stop|restart|status]"
    ;;
esac

# End of file
