#!/bin/sh

memsize=`grep MemTotal /proc/meminfo | awk '{print $2}'`

memsize=`echo "$memsize*1024*0.75" | bc`

swapoff /dev/zram0

echo 1 > /sys/block/zram0/reset
echo $memsize > /sys/block/zram0/disksize

mkswap /dev/zram0
swapon /dev/zram0 -p 10
