#!/bin/sh
#
# wm independent hotkeys
#

# terminal emulator
super + {Return,KP_Enter}
    urxvt

# program launcher
super + space
    rofirun
#    dmenurun
# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd

# colorpick
super + shift + button1
    getcolor

# mpd cotrol
super + {F9,F10,F11,F12}
    cmus-remote {-u,-s,-r,-n}

# volume
super + {F6,F7,F8}
    volume {toggle,1-,1+}
{XF86AudioLowerVolume,XF86AudioRaiseVolume}
    volume {1-,1+}

super + F4
    notify-send "$(date '+%a %d %b %H:%M')"

# screen
Print
    FILE_NAME="s$(date +%s%N).png" ; ffmpeg -f x11grab -video_size 1366x768 -i $DISPLAY -vframes 1 /tmp/$FILE_NAME -y && cp /tmp/$FILE_NAME ~/s.png

ctrl + Print
    FILE_NAME="s$(date +%s%N).png" ; import /tmp/$FILE_NAME && cp /tmp/$FILE_NAME ~/s.png

# shortcuts
super + {F1,F5}
    {exec firefox&> /dev/null 2>&1,googleimg}
