#!/bin/sh
#
# wm independent hotkeys
#

# terminal emulator
super + {Return,KP_Enter}
	urxvtc

# program launcher
super + space
    dmenu_run -q -dim 1 -nb "#080808" -nf "#dbdbdb" -sb "#dbdbdb" -sf "#080808" -x 433 -y 243 -h 25 -w 500 -l 10 -fn "DejaVu Sans:size=10"

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# rotate
super + r + {_,shift}
    bspc node -R {90,-90}

# quit bspwm normally
super + alt + Escape
	bspc quit

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# if the current node is automatic, send it to the last manual, otherwise pull the last leaf
super + y
	bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {x,y,z}
	bspc node -g {locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node
super + {_,shift + }c
	bspc node -f {next,prev}

# focus the next/previous desktop
super + bracket{left,right}
	bspc desktop -f {prev,next}

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused desktop
super + ctrl + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# resize tiled/floating
#

# expand the tiled space in the given direction
super + alt + {h,j,k,l}
	bspc node {@west -r -10,@south -r +10,@north -r -10,@east -r +10}

# contract the tiled space in the given direction
super + alt + shift + {h,j,k,l}
	# bspc node {@east -r -10,@north -r +10,@south -r -10,@west -r +10}

#
# pointer focus/move/resize
#

super + button{4-5}
    bspc config window_gap $(expr $(bspc config window_gap) {+,-} 1)

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

super + n
    bspc node -B

# colorpick
super + shift + button1
    ~/dotfiles/scripts/getcolor

# mpd cotrol
super + {F9,F10,F11,F12}
    mpc {toggle,stop,prev,next}

# volume
{XF86AudioRaiseVolume,XF86AudioLowerVolume}
    ~/dotfiles/scripts/volume 1{+,-}

# screen
{_,ctrl} + Print
    FILE_NAME="s$(($(date +%s%N)/1000000)).png" ; import {-window root,_} /tmp/$FILE_NAME && cp /tmp/$FILE_NAME ~/s.png

# shortcuts
super + {F1,F2,F3}
    {firefox-beta,pcmanfm,pavucontrol}
