#!/bin/sh

bspc config border_width 2
bspc config window_gap 6

bspc config focused_border_color "$(xrdb -query | grep "color7" | awk '{print $2}')"
bspc config normal_border_color "$(xrdb -query | grep "background" | head -n1 | awk '{print $2}')"

bspc config presel_feedback_color "$(xrdb -query | grep "color7" | awk '{print $2}')"

bspc config click_to_focus true
bspc config focus_follows_pointer true

bspc config borderless_monocle true
# bspc config gapless_monocle true
bspc config single_monocle true

bspc config honor_size_hints true

bspc monitor -d 1 2 3 4 5 6 7

bspc rule -a "Firefox:Navigator" desktop=^1 follow=on
bspc rule -a "chromium" desktop=^1 follow=on

bspc rule -a Atom desktop=^3 follow=on
bspc rule -a Subl3 desktop=^3 follow=on
bspc rule -a Sublime_text desktop=^3 follow=on
bspc rule -a Bless desktop=^3 state=tiled follow=on
bspc rule -a "*:libreoffice" desktop=^3 follow=on

bspc rule -a Filezilla desktop=^4 follow=on
bspc rule -a Zathura desktop=^4 state=tiled follow=on
bspc rule -a Pcmanfm desktop=^4 follow=on

bspc rule -a feh desktop=^5 follow=on
bspc rule -a mpv desktop=^5 follow=on

bspc rule -a Ghetto\ Skype desktop=^6 follow=on

bspc rule -a Gimp desktop=^7 follow=on
bspc rule -a MyPaint desktop=^7 follow=on
bspc rule -a Inkscape desktop=^7 follow=on

