#!/bin/sh

bspc config border_width            9
bspc config window_gap              9

bspc config top_padding             25

bspc config focused_border_color    \#08080b
bspc config normal_border_color     \#08080b

bspc config presel_feedback_color   \#e7e8eb

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config click_to_focus          true

bspc monitor -d          

bspc rule -a Firefox desktop= follow=on

bspc rule -a Zathura desktop= state=tiled follow=on
bspc rule -a Pcmanfm desktop= follow=on

bspc rule -a feh desktop= follow=on
bspc rule -a mpv desktop= follow=on

bspc rule -a krita desktop= follow=on
bspc rule -a MyPaint desktop= follow=on
bspc rule -a Inkscape desktop= follow=on
bspc rule -a Gimp desktop= follow=on

