#!/bin/sh

bspc config border_width            3
bspc config window_gap              0

bspc config top_padding             25

bspc config focused_border_color    \#2D3753
bspc config normal_border_color     \#0a0b10
bspc config presel_border_color     none

bspc config presel_feedback_color   \#2D3753

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config single_monocle          true

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc rule -a chromium desktop=0

bspc rule -a feh state=fullscreen
bspc rule -a mpv state=fullscreen

bspc rule -a Pavucontrol state=floating

bspc rule -a Steam desktop=4 state=floating
