#!/bin/bash
update() {
    chwb2 -I 080808  -O 080808 -i 3 -o 3 `bspc query -N -n .!descendant_of.window`
    chwb2 -I 080808  -O 2f558e -i 3 -o 3 `bspc query -N -n .descendant_of.window`
}

bspc subscribe node_geometry node_focus | while read msg; do
    update 2> /dev/null
done
